[package]
name = "agger-contracts"
version = "1.0.0"
authors = []

[addresses]
agger = "_"
[dev-addresses]
agger = "0xb3a402b1d4c7797b3cb5c8ea77e4a2ca5fd7fb9b8def568d4339a50fc387aa59"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
